//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_card
    {
        public int ID { get; set; }
        public string Illness { get; set; }
        public System.DateTime Beginning_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public int Patient_ID { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
