//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicEntities1 : DbContext
    {
        private static ClinicEntities1 _context;
        public ClinicEntities1()
            : base("name=ClinicEntities1")
        {
        }

        public static ClinicEntities1 GetContext()
        {
            if (_context == null)
                _context = new ClinicEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Job_titles> C_Job_titles { get; set; }
        public virtual DbSet<Appointment_results> Appointment_results { get; set; }
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Discharges> Discharges { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Medical_card> Medical_card { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Specialities> Specialities { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
